name: Create and Initialize New Repository

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Enter a new repo name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEMPLATE_REPO_NAME: test-terraform-actions
      NEW_REPO_NAME: test-terraform-${{ github.event.inputs.repo_name }}

    steps:
    - name: Checkout template repository
      uses: actions/checkout@v2
      with:
        repository: sskyh0208/$TEMPLATE_REPO_NAME

    - name: Push to new repository
      run: |
        cd $GITHUB_WORKSPACE
        git push --mirror https://github.com/sskyh0208/$NEW_REPO_NAME.git
