name: Create and Initialize New Repository

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Enter a deploy env name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create .env file
      run: |
        echo "AWS_ACCESS_KEY_ID=xxxx" >> .env
        echo "AWS_SECRET_ACCESS_KEY=xxxx" >> .env
        echo "AWS_DEFAULT_REGION=ap-northeast-1" >> .env

    - name: Build and run Docker Compose
      run: |
        make init
